### ISSUE TITLE
Document Usage

### ISSUE THREAD

**Issue by freaktechnik** [mozillach/gh-projects-content-queue#25]
- [x] document how to set the tool up in the readme. Currently partially done.
- [x] document our application and workflow on the mozilla.ch wikipage (new subpage)

**Comment by freaktechnik** [comment]
The usage workflow has been documented as https://gist.github.com/freaktechnik/aa029f23fc7d711b75792512bdb31588

**Comment by MichaelKohler** [comment]
Does it make sense to link this as example from the Readme?

**Comment by freaktechnik** [comment]
Potentially, though that would be part of #73 in my opinion.
