### ISSUE TITLE
npm test failed

### ISSUE THREAD

**Issue by kelimuttu** [mozillach/gh-projects-content-queue#43]
I've been trying this repo to see how this works. I've changed the [config.default.json property](https://github.com/mozillach/gh-projects-content-queue/blob/master/config.default.json) value to reflect my credentials. But when I try to run the test, it was failed. See [this](https://pageshot.net/St4TAENNyCnZbEPz/file) screenshot for detailed result. Can someone point me out where did I do wrong?

**Comment by freaktechnik** [comment]
The testrunner is ava (https://github.com/avajs/ava). Can you try running ava in serial and verbose mode?

**Comment by freaktechnik** [comment]
Did you rename the config.default.json or change the structure?

**Comment by freaktechnik** [comment]
(because tests are ran against it, but no working co fig is required for tests)

**Comment by kelimuttu** [comment]
That means that the test should be working regardless the config, right? However, I still experience the same error with verbose & serial mode. I suspect it's probably because of my node version (which is 6.9.1). I will try to upgrade it and see what happened by then.

**Comment by kelimuttu** [comment]
And yes, the docs would probably need to be updated. At least, these are the things that I'm not really sure when I try this project initially: 
- Should we rename the config.default.json file into config.json or should we duplicate and rename it?
- Where should we put the twitter content (should we put it in the code or can we do it through the project of the repo automatically?)

**Comment by freaktechnik** [comment]
That would mosz likely be why tests don't work. This project relies on async functikns, which are enabled by default from v7.7 of node (and 8.0 is the release version now...)

I am not sure what you mean by twitter content.

**Comment by MichaelKohler** [comment]
@freaktechnik do we have an example in our documentation on how the different formats of the issues to create look like? I know we create an issue template in the repository. I think that would help a lot :)

@kelimuttu hiii Kiki, good to see you here. You might want to have a look at freaktechnik's test repository regarding how the issue and boards look like (that is what will be tweeted): https://github.com/freaktechnik/content-queue-test

**Comment by freaktechnik** [comment]
@MichaelKohler There is no way to configure the format of the actual issue. All you have to give is the date format.

**Comment by kelimuttu** [comment]
Ok. The problem was indeed in the node version. I'm sorry for the fuss and thanks for the swift response.  

@MichaelKohler Thanks for pointing me out to the repo. That's exactly what I need. 

@freaktechnik mind to explain how is the project board works? Should we put the issue under certain column? and is the label will affect how's the issue work?

**Comment by freaktechnik** [comment]
Only columns affect what happens with the issue. Namely only the to Tweet column. All other columns are freely usable, though some of the features add tweets to other columns (like mentions, new issues that are in no column, tweeted tweets etc.) Labels are mainly used to convey state of the issue outward, though I can't say on the spot if they are used as flags in the code (it's been quite some time since I wrote that).

**Comment by kelimuttu** [comment]
I got another error after the test is working. 

"Repository ready Not all required OAuth scopes are granted. Please check your authentication.
ContentQueue setup Not all required OAuth scopes are granted. Please check your authentication."

I gave all the permission in the github token, tho'. Is there any specific thing I need to grant?

**Comment by freaktechnik** [comment]
It requires the "public_repo" scope, which is probably superseded when "repo" is granted and it currently does not understand that. Please open a new issue for that, since that's not tests related.
