### ISSUE TITLE
Add new meetup (or reps.mozilla.org?) events to a dedicated column

### ISSUE THREAD

**Issue by freaktechnik** [mozillach/gh-projects-content-queue#5]
They should be inserted a configurable multiple times, due at a different time.

**Comment by MichaelKohler** [comment]
Not sure how easy Meetup is in terms of API. For Reps we could use the calendar files.

**Comment by freaktechnik** [comment]
The upside for reps is that the provider for this should just he ics based, which would also give easy integration with a plethora of other tools like todo lists etc.

**Comment by freaktechnik** [comment]
It should be able to insert a self-retweet of a previous issue, so it's very easy to come up with two tweets.
