### ISSUE TITLE
Use only labels instead of Project board

### ISSUE THREAD

**Issue by Mte90** [mozillach/gh-projects-content-queue#54]
Instead of projects can be more easy use the label, like schedule or tweet it.
In that way to manage the issue it is possible to use also other interface to github issues.

**Comment by freaktechnik** [comment]
The reason I want to use the board is so the tweets are ordered in the to tweet column. It currently is not used and I'm not sure if it will be used for the reps use case, but that's why the board was used from the start.

**Comment by Mte90** [comment]
Good point I don't thought about the order but in that case maybe the assign time of the label can do the trick but will be no easy.

**Comment by freaktechnik** [comment]
There is also another thing about labels: they have an n:n releation with issues, while columns have an n:1 relation, meaning any single issue can only be in one column, removing some validation and, honestly, complicated edge-case handling.

**Comment by freaktechnik** [comment]
Closing due to the n:n relation issue. Thinking about ways to simplify usage with mobile devices is still worthwhile, though (since github hasn't show big interest in making their platform mobile-accessible)
