### ISSUE TITLE
One GitHub user per project or one user per instance

### ISSUE THREAD

**Issue by freaktechnik** [mozillach/gh-projects-content-queue#7]
Should this use one GitHub user per project or per instance? From a security standpoint I don't think it makes a difference, since the tokens for all accounts would be in the same config either way.

Currently it uses a user per project, which also means a GitHub client per account.

**Comment by MichaelKohler** [comment]
I think one per account is good, given the fact that we might go into the "reminder" direction. Then we could have a different user per repository reminding people with comments.
