### ISSUE TITLE
Be a GitHub Integration

### ISSUE THREAD

**Issue by freaktechnik** [mozillach/gh-projects-content-queue#77]
Once there's a WebInterface this might as well be a GitHub integration, though that also means being publically available from what I understand.

**Comment by freaktechnik** [comment]
This would make it harder to use within the mozilla organization, unless we can convince someone to approve the integration...

**Comment by MichaelKohler** [comment]
I would say that is almost not possible..

**Comment by freaktechnik** [comment]
Closing in favor of #186
